---
title: "Project: Social Squirrels"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

Data 1

**- Introduction and data**

\- Identify the source of the data.

-   This data was taken from NYC OpenData

\- State when and how it was originally collected (by the original data curator, not necessarily how you found the data).

-   This data was originally collected in 2018 as a part of The Squirrel Census. It was collected by volunteer "squirrel sighters" who observed hundreds of squirrels.

\- Write a brief description of the observations.

-   Each observation in this dataset represents one squirrel sighting. The data contains info on the location and time the squirrel was sighted, what it was doing, what sounds it was making, and many other things.

-   

    Method

\## Research question

**- Methodology**

\- A well formulated research question. (You may include more than one research question if you want to receive feedback on different ideas for your project. However, one per data set is required.)

-   Are juvenile squirrels friendlier to humans than adult squirrels? How does this manifest in their behavior?

\- A description of the research topic along with a concise statement of your hypotheses on this topic.

-   The research topic is about friendliness, innocence, and age in squirrels. We predict that younger squirrels will be less friendly around humans because they have not yet learned that these humans are largely harmless and (at times) give food. We predict this because we can observe this behavior in younger humans since younger kids tend to be less informed about their surroundings, and therefore will lean towards being more cautious of things. We would have to look into this data to confirm any of these predictions. The complete opposite of this prediction might be true.

\- Identify the types of variables in your research question. Categorical? Quantitative?

-   The variables involved in this research question are Age, Approaches, Indifferent, and Runs from. These are all categorical variables. The latter three variables all describe behavior around humans.

\## Literature

\- Find one published credible article on the topic you are interested in researching.

-   https://www.purchase.edu/live/files/2328-scalice-benson-and-howard-2018pdf

\- Provide a one paragraph summary about the article.

-   This is an article about research conducted at the SUNY Purchase College in Westchester, NY about how squirrels have become increasingly tolerant toward a human presence. In their study, they sampled a total of 20 squirrels, 10 of which were taken from an urban environment, and 10 of which were taken from a rural environment. The data collected in this study found that urban squirrels were able to tolerate a smaller distance between them and a human presence than rural squirrels. It was also observed that the time it took a squirrel to react to the human presence was more delayed for the urban squirrels than the rural squirrels. This study shows a certain level of adaptability and behavior adjustment that squirrels experience depending on their environment. This article certainly leads to further questions like our research question about when this behavior is learned and what factors into this adaptation.

\- In 1-2 sentences, explain how your research question builds on / is different than the article you have cited.

-   Our research question builds on the research conducted in this article because it questions if this adaptation and tolerance of a human presence is different for older and younger squirrels. Using The Squirrel Census, we can compare the behaviors toward humans for juvenile and adult squirrels.

**- Results**

**- W+F**
